name: Run Script with FFmpeg

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: prod
    env:
      UTUBE_URL: ${{vars.YOUTUBE_URL}}
      GH_ACCESS_TOKEN: ${{secrets.GH_ACCESS_TOKEN}}
    steps:
      - name: Verify environment
        run : |
          echo "Environment variable YOUTUBE_URL: $UTUBE_URL"
      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Install FFmpeg
      #   run: sudo apt-get install ffmpeg -y

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.x

      # - name: Install dependencies
      #   run: pip install -r requirements.txt

      # - name: Run script with FFmpeg
      #   run: |
      #     # Add your script execution command here
      #     python main.py
